### ISSUE TITLE
Add Support for LEFT OUTER JOIN

### ISSUE THREAD

**Issue by apavlo** [cmu-db/noisepage#1000]
We need to add support for `LEFT OUTER JOIN` so that we can run the CTE-converted queries. It currently looks like these queries do not get past the optimizer. So we will need to fix that first.

We will then need to extend the codegen layer + execution engine to support these types of joins. @amlatyrngom can provide additional information on what we need to modify in the execution engine to do this.

```
terrier=# CREATE TABLE xxx (id INT PRIMARY KEY, val INT);         
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1,1),(2,2),(3,3),(4,4);         
INSERT 0 4
terrier=# CREATE TABLE yyy (id INT PRIMARY KEY, val INT);   
CREATE TABLE
terrier=# INSERT INTO yyy VALUES (1,1),(2,2),(4,4);    
INSERT 0 4
terrier=# SELECT * FROM xxx LEFT OUTER JOIN yyy ON xxx.id = yyy.id;
<< DEAD >>
```

**Server Output:**
```
^[[A^[[BASAN:DEADLYSIGNAL
=================================================================
==31490==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x55b68474ec27 bp 0x7fabea9a6b70 sp 0x7fabea9a6b60 T7)
==31490==The signal is caused by a READ memory access.
==31490==Hint: address points to the zero page.
    #0 0x55b68474ec26 in terrier::common::ManagedPointer<terrier::optimizer::AbstractOptimizerNodeContents>::operator->() const /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/managed_pointer.h:48
    #1 0x55b6847866e0 in terrier::optimizer::Optimizer::ChooseBestPlan(terrier::transaction::TransactionContext*, terrier::catalog::CatalogAccessor*, terrier::common::StrongTypeAlias<terrier::optimizer::tags::group_id_t_typedef_tag, int>, terrier::optimizer::PropertySet*, std::vector<terrier::common::ManagedPointer<terrier::parser::AbstractExpression>, std::allocator<terrier::common::ManagedPointer<terrier::parser::AbstractExpression> > > const&) /home/pavlo/Documents/Peloton/Github/terrier/src/optimizer/optimizer.cpp:72
    #2 0x55b68478600b in terrier::optimizer::Optimizer::BuildPlanTree(terrier::transaction::TransactionContext*, terrier::catalog::CatalogAccessor*, terrier::optimizer::StatsStorage*, terrier::optimizer::QueryInfo, std::unique_ptr<terrier::optimizer::AbstractOptimizerNode, std::default_delete<terrier::optimizer::AbstractOptimizerNode> >) /home/pavlo/Documents/Peloton/Github/terrier/src/optimizer/optimizer.cpp:55
    #3 0x55b6844b8298 in terrier::trafficcop::TrafficCopUtil::Optimize(terrier::common::ManagedPointer<terrier::transaction::TransactionContext>, terrier::common::ManagedPointer<terrier::catalog::CatalogAccessor>, terrier::common::ManagedPointer<terrier::parser::ParseResult>, terrier::common::StrongTypeAlias<terrier::catalog::tags::db_oid_t_typedef_tag, unsigned int>, terrier::common::ManagedPointer<terrier::optimizer::StatsStorage>, std::unique_ptr<terrier::optimizer::AbstractCostModel, std::default_delete<terrier::optimizer::AbstractCostModel> >, unsigned long) /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop_util.cpp:68
    #4 0x55b68449f247 in terrier::trafficcop::TrafficCop::OptimizeBoundQuery(terrier::common::ManagedPointer<terrier::network::ConnectionContext>, terrier::common::ManagedPointer<terrier::parser::ParseResult>) const /home/pavlo/Documents/Peloton/Github/terrier/src/traffic_cop/traffic_cop.cpp:141
    #5 0x55b6842e8ffc in terrier::network::SimpleQueryCommand::Exec(terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter>, terrier::common::ManagedPointer<terrier::network::PostgresPacketWriter>, terrier::common::ManagedPointer<terrier::trafficcop::TrafficCop>, terrier::common::ManagedPointer<terrier::network::ConnectionContext>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_network_commands.cpp:146
    #6 0x55b6843343a8 in terrier::network::PostgresProtocolInterpreter::Process(terrier::common::ManagedPointer<terrier::network::ReadBuffer>, terrier::common::ManagedPointer<terrier::network::WriteQueue>, terrier::common::ManagedPointer<terrier::trafficcop::TrafficCop>, terrier::common::ManagedPointer<terrier::network::ConnectionContext>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/postgres/postgres_protocol_interpreter.cpp:45
    #7 0x55b684d972ad in terrier::network::ConnectionHandle::Process() /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:122
    #8 0x55b684d92c4f in operator() /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
    #9 0x55b684d92c6e in _FUN /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:105
    #10 0x55b684d94aa5 in terrier::network::ConnectionHandle::StateMachine::Accept(terrier::network::Transition, terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_handle.cpp:155
    #11 0x55b684749aba in terrier::network::ConnectionHandle::HandleEvent(int, short) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:97
    #12 0x55b684d9733d in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #13 0x55b684d9736c in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/network/connection_handle.h:153
    #14 0x7fac736e48f7  (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1e8f7)
    #15 0x7fac736e533e in event_base_loop (/usr/lib/x86_64-linux-gnu/libevent-2.1.so.6+0x1f33e)
    #16 0x55b684731cd1 in terrier::EventUtil::EventBaseDispatch(event_base*) /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/event_util.h:92
    #17 0x55b684731d6c in terrier::common::NotifiableTask::EventLoop() /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:159
    #18 0x55b6847495d3 in terrier::common::NotifiableTask::RunTask() /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/notifiable_task.h:166
    #19 0x55b6847321c1 in terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}::operator()() const /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/dedicated_thread_registry.h:83
    #20 0x55b6847339ae in void std::__invoke_impl<void, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(std::__invoke_other, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) /usr/include/c++/7/bits/invoke.h:60
    #21 0x55b684732e5f in std::__invoke_result<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>::type std::__invoke<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) /usr/include/c++/7/bits/invoke.h:95
    #22 0x55b684734e19 in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/7/thread:234
    #23 0x55b684734dea in std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::operator()() /usr/include/c++/7/thread:243
    #24 0x55b684734dc9 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> > >::_M_run() /usr/include/c++/7/thread:186
    #25 0x7fac729706de  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd6de)
    #26 0x7fac7391e6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #27 0x7fac7202d88e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12188e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/managed_pointer.h:48 in terrier::common::ManagedPointer<terrier::optimizer::AbstractOptimizerNodeContents>::operator->() const
Thread T7 created by T6 here:
    #0 0x7fac73b6dd2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7fac72970994 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd994)
    #2 0x55b684732549 in terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>) /home/pavlo/Documents/Peloton/Github/terrier/src/include/common/dedicated_thread_registry.h:81
    #3 0x55b6847312c8 in terrier::network::ConnectionDispatcherTask::RunTask() /home/pavlo/Documents/Peloton/Github/terrier/src/network/connection_dispatcher_task.cpp:55
    #4 0x55b68435c12e in terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}::operator()() const (/home/pavlo/Documents/Peloton/Github/terrier/build/debug/terrier+0xb1c12e)
    #5 0x55b68435f158 in void std::__invoke_impl<void, terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}>(std::__invoke_other, terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}&&) (/home/pavlo/Documents/Peloton/Github/terrier/build/debug/terrier+0xb1f158)
    #6 0x55b68435d9da in std::__invoke_result<terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}>::type std::__invoke<terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}>(terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}&&) /usr/include/c++/7/bits/invoke.h:95
    #7 0x55b6843649fd in decltype (__invoke((_S_declval<0ul>)())) std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/7/thread:234
    #8 0x55b6843649ce in std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}> >::operator()() /usr/include/c++/7/thread:243
    #9 0x55b6843649ad in std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>)::{lambda()#1}> > >::_M_run() /usr/include/c++/7/thread:186
    #10 0x7fac729706de  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd6de)

Thread T6 created by T0 here:
    #0 0x7fac73b6dd2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7fac72970994 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbd994)
    #2 0x55b68435c5e8 in terrier::common::ManagedPointer<terrier::network::ConnectionDispatcherTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionDispatcherTask, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry> >(terrier::common::DedicatedThreadOwner*, unsigned int, int, terrier::network::TerrierServer*, terrier::common::ManagedPointer<terrier::network::ProtocolInterpreter::Provider>, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>, terrier::common::ManagedPointer<terrier::common::DedicatedThreadRegistry>) (/home/pavlo/Documents/Peloton/Github/terrier/build/debug/terrier+0xb1c5e8)
    #3 0x55b68435a92e in terrier::network::TerrierServer::RunServer() /home/pavlo/Documents/Peloton/Github/terrier/src/network/terrier_server.cpp:74
    #4 0x55b6842a4fc5 in terrier::DBMain::Run() /home/pavlo/Documents/Peloton/Github/terrier/src/main/db_main.cpp:16
    #5 0x55b6840f2a9b in main /home/pavlo/Documents/Peloton/Github/terrier/src/main/terrier.cpp:89
    #6 0x7fac71f2db96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

==31490==ABORTING
```

**Comment by lmwnshn** [comment]
Fixed by #1100.
